pk_column: UUID
columns:
  - name: ID
    dtype: VARCHAR(255)
    formatter: ID
    extra: PRIMARY KEY

  - name: Tidspunkt
    dtype: DATE
    formatter: Tidspunkt
    extra: NOT NULL

  - name: Retning
    dtype: NUMBER
    formatter: Retning
    extra: NOT NULL

  - name: Posisjon
    dtype: SDO_GEOMETRY
    formatter: Posisjon
    extra: NOT NULL
    spatial_metadata:
      dimension: 3
      srid: 4326

  - name: FylkeNummer
    dtype: NUMBER
    formatter: FylkeNummer
    extra: NOT NULL

  - name: Vegkategori
    dtype: VARCHAR(255)
    formatter: Vegkategori
    extra: NOT NULL

  - name: Vegstatus
    dtype: VARCHAR(255)
    formatter: Vegstatus
    extra: NOT NULL

  - name: Vegnummer
    dtype: NUMBER
    formatter: Vegnummer
    extra: NOT NULL

  - name: StrekningReferanse
    dtype: VARCHAR(255)
    formatter: StrekningReferanse
    extra: NOT NULL

  - name: Meter
    dtype: NUMBER
    formatter: Meter
    extra: NOT NULL

  - name: Mappenavn
    dtype: VARCHAR(255)
    formatter: Mappenavn
    extra: NOT NULL

  - name: Filnavn
    dtype: VARCHAR(255)
    formatter: Filnavn
    extra: NOT NULL

  - name: JsonData
    dtype: CLOB
    formatter: JsonData
    extra: NOT NULL

  - name: ReflinkID
    dtype: NUMBER
    formatter: ReflinkID
    extra:

  - name: ReflinkPosisjon
    dtype: NUMBER
    formatter: ReflinkPosisjon
    extra:

  - name: DetekterteObjekter
    dtype: CLOB
    formatter: DetekterteObjekter
    extra:

  - name: Aar
    dtype: NUMBER
    formatter: Aar
    extra: NOT NULL

  - name: Feltkode
    dtype: VARCHAR(255)
    formatter: Feltkode
    extra: NOT NULL

  - name: Versjon
    dtype: VARCHAR(16)
    formatter: Versjon
    extra: